# Site title and subtitle. This is used in _includes/header.html
#
# to create a new page, use this format:
# ruby bin/jekyll-page "name of page" section
#
title: 'Journey Builder for Apps iOS SDK Documentation'

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# if you use google analytics, add your tracking id here
google_analytics_id: ''

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 0

# URL to source code, used in _includes/footer.html
codeurl: 'https://salesforcefuel.github.io/JB4A-SDK-iOS'

# Default categories (in order) to appear in the navigation
sections: []

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: "/JB4A-SDK-iOS" # the subpath of your site, e.g. /blog/
url: "http://exacttarget.github.io" # the base hostname & protocol for your site

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: pygments

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the kramdown Markdown renderer
markdown: kramdown
